# Generated by Django 5.1.2 on 2024-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_community_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='feed_every',
            field=models.IntegerField(default=8),
        ),
    ]
