# Generated by Django 5.1.2 on 2024-10-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pet_fed_at_alter_pet_community_alter_pet_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
